title: kobadbadbadbad
email: kobad.dogsy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  kobad Diary and Memo...
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

author:
  name: kobadlve
  email: kobad.dogsy@gmail.com
  github: kobadlve

paginate: 10
paginate_path: page:num

sass:
  style: expanded

markdown: kramdown

syntax_highlighter: rouge

gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
